prepare:
  samples_per_class: 200
  source_path: 
    E:\ULTIMATE_PROJECT\wildlife-identification-kamchatka\full_dataset

train:
  model_name: efnet
  epochs: 25
  batch_size: 32
  learning_rate: 0.0001
